### ISSUE TITLE
Device security D-Bus property name is misleading

### ISSUE THREAD

**Issue by gicmo** [gicmo/bolt#38]
Similar to #37 
Three options: 
- Keep it, but call it `DomainSecurity`
- Add `Domain` property and expose the Domain (with the security level as dbus object)
- All of the above.

**Comment by ybernat** [comment]
IMHO, a way to find the domain from the device makes more sense as it may be useful for more domain-related info, not only for the security level.
(But I'd expect it to be possible to deduce the domain from the route-string, for example, or maybe there is even a D-Bus mechanism for it if the device is exposed as a child of the domain.)

**Comment by gicmo** [comment]
> IMHO, a way to find the domain from the device makes more sense as it may be useful for more domain-related info, not only for the security level.

I agree! The only one thing why keeping `DomainSecurity` would be nice, is as convenience for the clients, so they don't have to go and open the domain object from the device object "just" to display the security level.
