### ISSUE TITLE
meson build warning

### ISSUE THREAD

**Issue by setharnold** [gicmo/bolt#74]
Hello, the Ubuntu packaging reports a warning during build:

```
meson.build:355: WARNING: Trying to compare values of different types (str, bool) using !=.
```

The line in question appears to be:

```
build_man = build_man != false and a2x.found()
```

Thanks

**Comment by gicmo** [comment]
Thanks a lot for reporting this, highly appreciated. I believe this is fixed with commit 667dd6c5c386f8c85650ad0622ad3a2280b2f06c 
Thanks!
